version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: local_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432" # Exposing PostgreSQL on port 5433
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - aivms_net

  redis:
    image: redis:7
    container_name: local_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - aivms_net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: local_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # management UI
    networks:
      - aivms_net

volumes:
  pg_data:

networks:
  aivms_net:
    driver: bridge
